import './globals.scss'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import AuthProvider from '@/components/AuthProvider/AuthProvider';
import { Navigation } from '@/components/Navigation/Navigation';
import { getServerSession } from 'next-auth';
import { authOptions } from '@/app/api/auth/[...nextauth]/route';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout(props: {
  children: React.ReactNode
}) {
  const session = await getServerSession(authOptions);
  const { children } = props;
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider session={session}>
          <Navigation/>
          {children}
        </AuthProvider>
      </body>
    </html>
  )
}
